/**
 * ana pr create - Create GitHub PR from pipeline artifacts
 *
 * Usage:
 *   ana pr create {slug}
 *
 * Exit codes:
 *   0 - Success (PR created)
 *   1 - Error (missing files, verification not PASS, gh not available)
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { readArtifactBranch, readBranchPrefix, getCurrentBranch, readCoAuthor, runGit } from '../utils/git-operations.js';
import { generateProofSummary, type ProofSummary } from '../utils/proofSummary.js';
import { findProjectRoot, validateSlug } from '../utils/validators.js';

/**
 * Extract PR Summary section from build report
 *
 * @param content - Build report content
 * @returns PR Summary bullets or fallback text
 */
function extractPrSummary(content: string): string {
  const match = content.match(/## PR Summary\s*\n([\s\S]*?)(?=\n## |$)/);
  if (match && match[1] && match[1].trim()) {
    return match[1].trim();
  }
  return 'See build report for details.';
}

/**
 * Extract Result line from verify report
 *
 * @param content - Verify report content
 * @returns Result (PASS/FAIL) or null
 */
function extractVerifyResult(content: string): string | null {
  const match = content.match(/\*\*Result:\*\*\s*(PASS|FAIL)/i);
  return match && match[1] ? match[1].toUpperCase() : null;
}

/**
 * Extract test count info from verify report
 *
 * @param content - Verify report content
 * @returns Test count line or fallback
 */
function extractTestInfo(content: string): string {
  const match = content.match(/Tests:\s*(\d+\s+passed[^\\n]*)/i);
  return match && match[1] ? match[1] : 'See verify report';
}

/**
 * Count phases from plan.md
 *
 * @param content - Plan.md content
 * @returns Number of phases
 */
function countPhases(content: string): number {
  const matches = content.match(/Spec:/g);
  return matches ? matches.length : 1;
}

/**
 * Extract title from scope.md
 *
 * @param content - Scope.md content
 * @returns Title string
 */
function extractTitle(content: string): string {
  // Try first # heading
  const headingMatch = content.match(/^#\s+(.+)$/m);
  if (headingMatch && headingMatch[1]) {
    return headingMatch[1].trim().replace(/^Scope:\s*/i, '');
  }

  // Try ## Intent section first line
  const intentMatch = content.match(/## Intent\s*\n(.+)/);
  if (intentMatch && intentMatch[1]) {
    return intentMatch[1].trim();
  }

  return 'See scope for details';
}

/**
 * Render proof summary as GitHub-flavored markdown
 *
 * @param proof - Proof summary data
 * @returns Markdown string for PR body
 */
function renderProofMarkdown(proof: ProofSummary): string {
  const lines: string[] = [];

  lines.push(`## Anatomia Proof — ${proof.feature}`);
  lines.push('');

  const satisfied = proof.contract.satisfied;
  const total = proof.contract.total;
  const acMet = proof.acceptance_criteria.met;
  const acTotal = proof.acceptance_criteria.total;
  const devCount = proof.deviations.length;

  const icon = proof.result === 'PASS' ? '✅' : '❌';
  lines.push(`${icon} **${proof.result}** · ${satisfied}/${total} assertions satisfied · ${acMet}/${acTotal} ACs met · ${devCount} deviation${devCount !== 1 ? 's' : ''}`);
  lines.push('');

  // Contract Compliance table
  if (proof.assertions.length > 0) {
    lines.push('### Contract Compliance');
    lines.push('| ID | Says | Status |');
    lines.push('|----|------|--------|');

    for (const a of proof.assertions) {
      const status = a.verifyStatus || 'UNVERIFIED';
      let statusIcon = '✅';
      if (status === 'UNSATISFIED' || status === 'UNCOVERED') statusIcon = '❌';
      if (status === 'DEVIATED') statusIcon = '⚠️';
      if (status === 'UNVERIFIED') statusIcon = '❓';
      lines.push(`| ${a.id} | ${a.says} | ${statusIcon} ${status} |`);
    }

    lines.push('');
  }

  // Deviations
  if (proof.deviations.length > 0) {
    lines.push('### Deviations');
    for (const d of proof.deviations) {
      lines.push(`**${d.contract_id}:** "${d.says}" → "${d.instead || 'not specified'}"`);
      if (d.reason) lines.push(`Reason: ${d.reason}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [Anatomia](https://anatomia.dev) · Ship with proof.*');

  return lines.join('\n');
}

/**
 * Create a GitHub PR from pipeline artifacts
 *
 * @param slug - Work item slug
 */
export function createPr(slug: string): void {
  // 0. Validate slug format
  try {
    validateSlug(slug);
  } catch {
    console.error(chalk.red('Error: Invalid slug format. Use kebab-case: fix-auth-timeout, add-export-csv'));
    process.exit(1);
  }

  const projectRoot = findProjectRoot();

  // 1. Read artifactBranch from ana.json
  const artifactBranch = readArtifactBranch(projectRoot);

  // 2. Get current branch and derive slug if needed
  const currentBranch = getCurrentBranch();
  if (!currentBranch) {
    console.error(chalk.red('Error: Not a git repository.'));
    process.exit(1);
  }

  // Warn if not on a work branch (slug-based check — prefix-independent)
  if (!(currentBranch.endsWith('/' + slug) || currentBranch === slug)) {
    console.log(chalk.yellow(`Warning: Current branch is '${currentBranch}' (expected a branch ending with '${slug}').`));
  }

  // 2b. Best-effort fetch + behind-count check
  try {
    runGit(['fetch', 'origin', artifactBranch, '--quiet']);
  } catch {
    // Silently continue if offline
  }
  try {
    const behindResult = runGit(['rev-list', '--count', `${currentBranch}..origin/${artifactBranch}`]);
    const behind = behindResult.exitCode === 0 ? parseInt(behindResult.stdout) || 0 : 0;
    if (behind > 0) {
      console.log(chalk.yellow(`⚠ Branch is ${behind} commit${behind !== 1 ? 's' : ''} behind ${artifactBranch}. Consider rebasing before merging.`));
    }
  } catch {
    // Silently continue on failure
  }

  // 3. Check gh CLI availability
  const ghCheck = spawnSync('gh', ['--version'], { stdio: 'pipe' });
  if (ghCheck.status !== 0) {
    console.error(chalk.red('Error: GitHub CLI (gh) not found.'));
    console.error(chalk.gray('Install from https://cli.github.com/'));
    process.exit(1);
  }

  // 3b. Check for existing PRs on this branch
  const branchPrefix = readBranchPrefix(projectRoot);
  const workBranch = currentBranch.endsWith('/' + slug) ? currentBranch : `${branchPrefix}${slug}`;
  const prListResult = spawnSync('gh', ['pr', 'list', '--head', workBranch, '--state', 'all', '--json', 'state,url'], {
    cwd: projectRoot, encoding: 'utf-8', stdio: 'pipe',
  });
  if (prListResult.status === 0 && prListResult.stdout) {
    try {
      const existingPrs = JSON.parse(prListResult.stdout.trim()) as Array<{ state: string; url: string }>;
      for (const pr of existingPrs) {
        if (pr.state === 'MERGED') {
          console.error(chalk.red(`Error: A PR for \`${workBranch}\` was already merged.`));
          console.error(chalk.gray(`Run \`ana work complete ${slug}\` to archive this work item.`));
          process.exit(1);
        }
        if (pr.state === 'OPEN') {
          console.error(chalk.red(`Error: A PR for \`${workBranch}\` is already open.`));
          console.error(chalk.gray(`  ${pr.url}`));
          process.exit(1);
        }
      }
    } catch {
      // JSON parse error — continue with PR creation
    }
  }

  // 4. Read verify report (single-spec: verify_report.md, multi-spec: verify_report_N.md)
  const planDir = path.join(projectRoot, '.ana/plans/active', slug);
  const dirFiles = fs.readdirSync(planDir);
  let verifyReportPath = path.join(planDir, 'verify_report.md');
  if (!fs.existsSync(verifyReportPath)) {
    // Multi-spec: find the highest-numbered verify report
    const verifyReports = dirFiles
      .filter(f => f.match(/^verify_report_\d+\.md$/))
      .sort();
    if (verifyReports.length > 0) {
      verifyReportPath = path.join(planDir, verifyReports[verifyReports.length - 1]!);
    } else {
      console.error(chalk.red('No verify report found.'));
      console.error(chalk.gray('Run `claude --agent ana-verify` first.'));
      process.exit(1);
    }
  }

  const verifyContent = fs.readFileSync(verifyReportPath, 'utf-8');
  const result = extractVerifyResult(verifyContent);

  if (!result) {
    console.error(chalk.red('Error: Verify report has no Result line.'));
    process.exit(1);
  }

  if (result !== 'PASS') {
    console.error(chalk.red(`Cannot create PR — verification result is ${result}.`));
    console.error(chalk.gray('Fix issues and re-verify before creating PR.'));
    process.exit(1);
  }

  const testInfo = extractTestInfo(verifyContent);

  // 5. Read build report (single-spec: build_report.md, multi-spec: build_report_N.md)
  let buildReportPath = path.join(planDir, 'build_report.md');
  if (!fs.existsSync(buildReportPath)) {
    // Multi-spec: find the highest-numbered build report
    const buildReports = dirFiles
      .filter(f => f.match(/^build_report_\d+\.md$/))
      .sort();
    if (buildReports.length > 0) {
      buildReportPath = path.join(planDir, buildReports[buildReports.length - 1]!);
    } else {
      console.error(chalk.red('No build report found.'));
      console.error(chalk.gray('Run `claude --agent ana-build` first.'));
      process.exit(1);
    }
  }

  const buildContent = fs.readFileSync(buildReportPath, 'utf-8');
  const prSummary = extractPrSummary(buildContent);

  // 6. Read plan.md to count phases
  const planPath = path.join(projectRoot, '.ana/plans/active', slug, 'plan.md');
  let phaseCount = 1;
  if (fs.existsSync(planPath)) {
    const planContent = fs.readFileSync(planPath, 'utf-8');
    phaseCount = countPhases(planContent);
  }

  // 7. Read scope.md to extract title
  const scopePath = path.join(projectRoot, '.ana/plans/active', slug, 'scope.md');
  let title = slug;
  if (fs.existsSync(scopePath)) {
    const scopeContent = fs.readFileSync(scopePath, 'utf-8');
    title = extractTitle(scopeContent);
  }

  // 8. Read coAuthor
  const coAuthor = readCoAuthor(projectRoot);

  // 9. Generate proof summary and render PR body
  const activeDir = path.join(projectRoot, '.ana/plans/active', slug);
  const proof = generateProofSummary(activeDir);

  // Build proof section (only if we have contract data)
  let proofSection = '';
  if (proof.assertions.length > 0) {
    proofSection = renderProofMarkdown(proof) + '\n\n';
  }

  const prBody = `${proofSection}## Summary
${prSummary}

## Pipeline Artifacts
- Scope: \`.ana/plans/active/${slug}/scope.md\`
- Spec: \`.ana/plans/active/${slug}/spec.md\`
- Build Report: \`${path.relative(projectRoot, buildReportPath)}\`
- Verify Report: \`${path.relative(projectRoot, verifyReportPath)}\`

## Verification
- **Result:** ${result}
- Phases: ${phaseCount} verified
- Tests: ${testInfo}

Co-authored-by: ${coAuthor}`;

  // 10. Create PR
  const prTitle = `[${slug}] ${title}`;
  const ghResult = spawnSync(
    'gh',
    ['pr', 'create', '--base', artifactBranch, '--head', currentBranch, '--title', prTitle, '--body', prBody],
    { cwd: projectRoot, stdio: 'pipe', encoding: 'utf-8' }
  );

  if (ghResult.status !== 0) {
    const errorOutput = ghResult.stderr || ghResult.stdout || '';

    // Check if PR already exists
    if (errorOutput.includes('already exists')) {
      console.log(chalk.yellow('PR already exists for this branch.'));

      // Try to get existing PR URL
      const viewResult = spawnSync('gh', ['pr', 'view', '--json', 'url', '-q', '.url'], {
        cwd: projectRoot,
        stdio: 'pipe',
        encoding: 'utf-8'
      });

      if (viewResult.status === 0 && viewResult.stdout.trim()) {
        console.log(chalk.cyan(`PR URL: ${viewResult.stdout.trim()}`));
        process.exit(0);
      }
    }

    // Other error - show it
    console.error(chalk.red('Error: Failed to create PR.'));
    console.error(errorOutput);
    process.exit(1);
  }

  // Success - extract URL from output
  const prUrl = ghResult.stdout.trim();
  console.log(chalk.green('✓ PR created'));
  console.log(chalk.cyan(prUrl));
}

/**
 * Register pr command with the CLI
 *
 * @param program - Commander program instance
 */
export function registerPrCommand(program: Command): void {
  const prCommand = new Command('pr')
    .description('Create pull request from verified build');

  prCommand
    .command('create')
    .description('Create GitHub PR from pipeline artifacts')
    .argument('<slug>', 'Work item slug (e.g., add-status-command)')
    .action((slug: string) => {
      createPr(slug);
    });

  program.addCommand(prCommand);
}
